#include "F_28x30_Digit.h"

 uint16_t bak=0xFFFF; 
 uint16_t fig=0x0000;

uint16_t image_data_Font_28x30_0x20[840] = {
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak
};

uint16_t image_data_Font_28x30_0x2e[840] = {
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak
};

uint16_t image_data_Font_28x30_0x2f[840] = {
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak
};

uint16_t image_data_Font_28x30_0x30[840] = {
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak
};

uint16_t image_data_Font_28x30_0x31[840] = {
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak
};

uint16_t image_data_Font_28x30_0x32[840] = {
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak
};

uint16_t image_data_Font_28x30_0x33[840] = {
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak
};

uint16_t image_data_Font_28x30_0x34[840] = {
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, 
    bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, 
    bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, 
    bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, 
    bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, 
    bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak
};

uint16_t image_data_Font_28x30_0x35[840] = {
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, bak, bak, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak
};

uint16_t image_data_Font_28x30_0x36[840] = {
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak
};

uint16_t image_data_Font_28x30_0x37[840] = {
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak
};

uint16_t image_data_Font_28x30_0x38[840] = {
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak
};

uint16_t image_data_Font_28x30_0x39[840] = {
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak
};

uint16_t image_data_Font_28x30_0x3a[840] = {
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, fig, fig, fig, fig, fig, fig, fig, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, 
    bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak, bak
};