#include "pardac.h"

ParDac::ParDac() {
    pardac_init();
}

void ParDac::pardac_init() {
    RCC->AHB4ENR|=RCC_AHB4ENR_GPIOEEN;
	GPIOE->MODER|=(GPIO_MODER_MODE0_0|GPIO_MODER_MODE1_0|GPIO_MODER_MODE2_0|GPIO_MODER_MODE3_0|GPIO_MODER_MODE4_0|
                   GPIO_MODER_MODE5_0|GPIO_MODER_MODE6_0);
    GPIOE->MODER&=~(GPIO_MODER_MODE0_1|GPIO_MODER_MODE1_1|GPIO_MODER_MODE2_1|GPIO_MODER_MODE3_1|GPIO_MODER_MODE4_1|
                   GPIO_MODER_MODE5_1|GPIO_MODER_MODE6_1); //0:1 output
    GPIOE->OSPEEDR |= (GPIO_OSPEEDR_OSPEED0|GPIO_OSPEEDR_OSPEED1|GPIO_OSPEEDR_OSPEED2|GPIO_OSPEEDR_OSPEED3|
                    GPIO_OSPEEDR_OSPEED4|GPIO_OSPEEDR_OSPEED5|GPIO_OSPEEDR_OSPEED6);// 1:1 max speed        
}